"""
This is a setup.py script generated by py2applet

Usage:
    python osxsetup.py py2app

within conda enviroment: use brew-installed pyside (v1.2.2), because PySide is not supported by conda anymore

"""
#import macholib_patch
import sys
sys.setrecursionlimit(2000)
from setuptools import setup

APP = ['Facepager.py']
DATA_FILES = [('',['docs']),('',['ssl'])]
OPTIONS = {'argv_emulation': False,
 'iconfile':'icon.icns',
 'includes': 'PySide2.QtCore,sqlite3,rauth,requests_oauthlib,credentials,dynlib	',
 'packages': 'sqlalchemy,dateutil'} #pandas.timedeltas

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
